# Generated by Django 4.1.7 on 2023-05-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_pw_confirm",
            field=models.CharField(
                default="", max_length=30, verbose_name="유저 비밀번호 확인"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=16, verbose_name="유저 이름"),
        ),
    ]
